/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.Ingrediente;
import backend.MateriaPrima;
import backend.Produto;
import backend.Manufatura;
import backend.Processo;
import backend.Operador;
import backend.Equipamento;
import java.util.ArrayList;




/**
 *
 * @author robo
 */
public class CadastrarProduto extends javax.swing.JFrame {

    ArrayList<Operador> listaOp;
    ArrayList<Processo> listaProcess;
    ArrayList<Manufatura> listaManu;
    ArrayList<Equipamento> listaEquip;

    /**
     * Creates new form CadastrarProduto
     */
    public CadastrarProduto() {
        initComponents();
    }
    
    public CadastrarProduto(ArrayList<Operador> listaOp, ArrayList<Equipamento> listaEquip){
        this.listaOp = listaOp;
        this.listaEquip = listaEquip;
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtCusto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIngredienteNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIngredienteUnidade = new javax.swing.JTextField();
        txtIngredientePreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIngredienteFornecedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIngredienteQuant = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bttIngredCad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtManufaturaProcesso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtManufaturaCusto = new javax.swing.JTextField();
        bttOp = new javax.swing.JButton();
        bttEquip = new javax.swing.JButton();
        bttManufaturaCadastrar = new javax.swing.JButton();
        bttCalcular = new javax.swing.JButton();
        bttVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Produto");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtCusto.setEditable(false);
        txtCusto.setBackground(new java.awt.Color(153, 153, 153));
        txtCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrediente"));

        jLabel3.setText("Nome:");

        txtIngredienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredienteNomeActionPerformed(evt);
            }
        });

        jLabel4.setText("Unidade:");

        txtIngredienteUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredienteUnidadeActionPerformed(evt);
            }
        });

        txtIngredientePreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredientePrecoActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço:");

        txtIngredienteFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredienteFornecedorActionPerformed(evt);
            }
        });

        jLabel6.setText("Fornecedor:");

        txtIngredienteQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredienteQuantActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade:");

        bttIngredCad.setText("Cadastrar");
        bttIngredCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttIngredCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIngredienteNome))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtIngredientePreco, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(29, 29, 29)
                                .addComponent(txtIngredienteQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtIngredienteUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIngredienteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttIngredCad)
                .addGap(155, 155, 155))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngredienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngredienteUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtIngredienteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngredientePreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtIngredienteQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(bttIngredCad)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setText("Nome:");

        jLabel2.setText("Custo:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Manufatura"));

        jLabel8.setText("Processo:");

        txtManufaturaProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufaturaProcessoActionPerformed(evt);
            }
        });

        jLabel9.setText("Custo por hora:");

        txtManufaturaCusto.setEditable(false);
        txtManufaturaCusto.setBackground(new java.awt.Color(153, 153, 153));

        bttOp.setText("Operador");
        bttOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttOpActionPerformed(evt);
            }
        });

        bttEquip.setText("Equipamento");
        bttEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEquipActionPerformed(evt);
            }
        });

        bttManufaturaCadastrar.setText("Cadastrar");
        bttManufaturaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttManufaturaCadastrarActionPerformed(evt);
            }
        });

        bttCalcular.setText("Calcular");
        bttCalcular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bttCalcularFocusLost(evt);
            }
        });
        bttCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtManufaturaProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtManufaturaCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bttOp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttManufaturaCadastrar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufaturaProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtManufaturaCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttOp)
                    .addComponent(bttEquip)
                    .addComponent(bttManufaturaCadastrar)
                    .addComponent(bttCalcular))
                .addGap(31, 31, 31))
        );

        bttVoltar.setText("Voltar");
        bttVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttVoltar)
                .addGap(230, 230, 230))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttVoltar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtIngredienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngredienteNomeActionPerformed

    private void txtIngredienteUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredienteUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngredienteUnidadeActionPerformed

    private void txtIngredientePrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredientePrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngredientePrecoActionPerformed

    private void txtIngredienteFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredienteFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngredienteFornecedorActionPerformed

    private void txtIngredienteQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredienteQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngredienteQuantActionPerformed

    private void txtManufaturaProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufaturaProcessoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtManufaturaProcessoActionPerformed

    private void bttVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVoltarActionPerformed
        // TODO add your handling code here:
        new Cadastrar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttVoltarActionPerformed

    private void bttIngredCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttIngredCadActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto(txtNome.getText());
        
        Ingrediente i = new Ingrediente(
                        new MateriaPrima(
                                txtIngredienteNome.getText(), 
                                txtIngredienteUnidade.getText(), 
                                txtIngredienteFornecedor.getText(), 
                                Float.parseFloat(txtIngredientePreco.getText())
                        ), 
                        Integer.parseInt(txtIngredienteQuant.getText())
                        );
        p.adicionaIngrediente(i);
        p.imprime();
    }//GEN-LAST:event_bttIngredCadActionPerformed

    private void bttManufaturaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttManufaturaCadastrarActionPerformed
        // TODO add your handling code here:
        
        //Instanciando os objetos
        Processo p = new Processo(listaOp.get(listaOp.size() - 1), listaEquip.get(listaEquip.size() - 1));
        
        p.setNome(txtManufaturaProcesso.getText());
        /* Manufatura m = new Manufatura(
                        new Processo(
                                nome, 
                                TOP_ALIGNMENT, 
                                operador, 
                                equipamento
                       ), 
                       TOP_ALIGNMENT);*/
        //p.imprime();

        //for (Operador operador : this.listaOp) {
        //    operador.imprime();
        //}
        //for (Equipamento equipamento : this.listaEquip) {
        //    equipamento.imprime();
        //}
        p.imprime();
    }//GEN-LAST:event_bttManufaturaCadastrarActionPerformed

    private void bttOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttOpActionPerformed
        // TODO add your handling code here:
        new CadastrarOperador(this.listaOp,this.listaEquip).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttOpActionPerformed

    private void bttEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEquipActionPerformed
        // TODO add your handling code here:
        new CadastrarEquipamento(this.listaOp,this.listaEquip).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttEquipActionPerformed

    private void txtCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustoActionPerformed

    private void bttCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCalcularActionPerformed
    
        //Instanciando os objetos
        Operador o = new Operador();
        Equipamento e = new Equipamento();
        Processo p = new Processo(o, e);

        for (Operador operador : this.listaOp) {
            operador.imprime();
        }
        for (Equipamento equipamento : this.listaEquip) {
            equipamento.imprime();
        }
        
        System.out.println(listaOp.size());
        System.out.println(listaEquip.size());
        
        //Atualizando os valores
        o.setSalarioHora(listaOp.get((listaOp.size() - 1)).getSalarioHora());
        e.setDepreciacaohora(listaEquip.get((listaEquip.size() - 1)).getDepreciacaoHora());
        
        System.out.println(o.getSalarioHora());
        System.out.println(e.getDepreciacaoHora());
        
        txtManufaturaCusto.setText(String.valueOf(p.calculaCusto()));

    }//GEN-LAST:event_bttCalcularActionPerformed

    private void bttCalcularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bttCalcularFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_bttCalcularFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCalcular;
    private javax.swing.JButton bttEquip;
    private javax.swing.JButton bttIngredCad;
    private javax.swing.JButton bttManufaturaCadastrar;
    private javax.swing.JButton bttOp;
    private javax.swing.JButton bttVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCusto;
    private javax.swing.JTextField txtIngredienteFornecedor;
    private javax.swing.JTextField txtIngredienteNome;
    private javax.swing.JTextField txtIngredientePreco;
    private javax.swing.JTextField txtIngredienteQuant;
    private javax.swing.JTextField txtIngredienteUnidade;
    private javax.swing.JTextField txtManufaturaCusto;
    private javax.swing.JTextField txtManufaturaProcesso;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
